<?php
//This file is autogenerated, do not modify
function nethttp_net_libs_addStyleAndScript()
{
	wp_enqueue_style('bootstrap', 'http://labeldessinges.dev.gie.im/wp-content/plugins/nethttp.net-libs/libs/bootstrap-5.2.3-dist/css/bootstrap.min.css',array (
), WP_DEBUG ? time() : '5.2.3');

	wp_enqueue_script('bootstrap-js', 'http://labeldessinges.dev.gie.im/wp-content/plugins/nethttp.net-libs/libs/bootstrap-5.2.3-dist/js/bootstrap.min.js', array (
), WP_DEBUG ? time() : '5.2.3', true);

	wp_enqueue_script('masonry-js', 'http://labeldessinges.dev.gie.im/wp-content/plugins/nethttp.net-libs/libs/masonry.pkgd.min.js', array (
  0 => 'jquery',
), WP_DEBUG ? time() : '', true);


}
function nethttp_net_libs_addStyleAndScript_admin()
{
if(isset($_GET['page']) && (stristr($_GET['page'],'label-des-singes')!=-1 || $_GET['page']=='nethttp.net-libs' )){
		wp_enqueue_style('bootstrap', 'http://labeldessinges.dev.gie.im/wp-content/plugins/nethttp.net-libs/libs/bootstrap-5.2.3-dist/css/bootstrap.min.css',array (
), WP_DEBUG ? time() : '5.2.3');

	wp_enqueue_script('bootstrap-js', 'http://labeldessinges.dev.gie.im/wp-content/plugins/nethttp.net-libs/libs/bootstrap-5.2.3-dist/js/bootstrap.min.js', array (
), WP_DEBUG ? time() : '5.2.3', true);


}
if(isset($_GET['page']) && stristr($_GET['page'],'label-des-singes')!=-1){
		wp_enqueue_script('jqueryui-js', 'http://labeldessinges.dev.gie.im/wp-content/plugins/nethttp.net-libs/libs/jquery-ui-1.13.2/dist/jquery-ui.min.js', array (
  0 => 'jquery',
), WP_DEBUG ? time() : '1.13.2', true);

	wp_enqueue_style('jqueryui', 'http://labeldessinges.dev.gie.im/wp-content/plugins/nethttp.net-libs/libs/jquery-ui-1.13.2/dist/themes/base/jquery-ui.min.css',array (
  0 => 'jquery',
), WP_DEBUG ? time() : '1.13.2');

	wp_enqueue_style('jqueryui-0', 'http://labeldessinges.dev.gie.im/wp-content/plugins/nethttp.net-libs/libs/jquery-ui-1.13.2/dist/themes/base/theme.css',array (
  0 => 'jquery',
), WP_DEBUG ? time() : '1.13.2');


}

}
add_action('admin_enqueue_scripts', 'nethttp_net_libs_addStyleAndScript_admin');
add_action('wp_enqueue_scripts', 'nethttp_net_libs_addStyleAndScript');
